name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Check Format by scalafmt
        run:
          sbt scalafmtSbtCheck scalafmtCheckAll
      - name: Check Lint by scalafix
        run:
          sbt scalafixEnable "scalafixAll --check"
      - name: Sbt tests
        run:
          sbt test