name: DOCS
on:
  push:
    branches: [ master ]
    paths: 
      - src/main/scala/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Generate Scaladoc
        run:
          sbt doc
      - name: Deploy pages
        env:
          GITHUB_IO_REPO_DEPLOY_KEY: ${{ secrets.DEPLOY_DOCS }}
          GIT_SSH_COMMAND: ssh -i ~/deploy_key.pem
        run: |
          echo "$GITHUB_IO_REPO_DEPLOY_KEY" > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem
          git config --global pull.rebase false
          git config --global user.email "iemura.java@gmail.com"
          git config --global user.name "Javakky"
          git clone "git@github.com:rapid-bout/Rapid-Bout-Core-Docs.git"
          cd Rapid-Bout-Core-Docs
          git checkout master
          git pull origin master
          cp -r ../docs ./
          git add -A
          git commit -m "Deploy $GITHUB_SHA by GitHub Actions"
          git push -f origin master
          